// mcf-worker.js — MatchBox Cloudflare Workers + Durable Objects Shell
// Auto-generated by SkyBox CLI.
//
// This file provides two exports:
//   1. default { fetch } — the stateless Worker entry point that
//      validates and upgrades WebSocket requests, then proxies to the DO.
//   2. MatchBoxWebSocketDO — the Durable Object class that hosts the
//      BoxLang VM and manages WebSocket connections via the Hibernation API.
//
// The WASM is loaded via wasm-bindgen's initSync() because workerd imports
// it as a CompiledWasm (WebAssembly.Module), not an instantiated instance.

import { initSync, vm_init, vm_set_state, vm_get_state, vm_register_connection, vm_on_connect, vm_on_message, vm_on_close } from './wasm_glue.js';
import wasmModule from './worker.wasm';

let wasmCompiledModule = null;
let wasmInitialized = false;

function getWasmSection(name) {
    if (!wasmCompiledModule) return null;
    const sections = WebAssembly.Module.customSections(wasmCompiledModule, name);
    if (sections.length === 0) return null;
    return new Uint8Array(sections[0]);
}

async function ensureWasmInit() {
    if (wasmInitialized) return;
    wasmCompiledModule = wasmModule;
    initSync({ module: wasmModule });
    const chunkBytes = getWasmSection('skybox:chunk');
    const configJson = getWasmSection('skybox:ws_config');
    if (chunkBytes && configJson) {
        const config = JSON.parse(new TextDecoder().decode(configJson));
        vm_init(JSON.stringify(config), chunkBytes);
    }
    wasmInitialized = true;
}

export class MatchBoxWebSocketDO {
    constructor(ctx, env) {
        this.ctx = ctx;
        this.env = env;
    }
    async fetch(request) {
        await ensureWasmInit();
        const pair = new WebSocketPair();
        const [client, server] = Object.values(pair);
        this.ctx.acceptWebSocket(server);
        const rd = {
            method: request.method,
            path: new URL(request.url).pathname,
            headers: Object.fromEntries(request.headers)
        };
        vm_register_connection(server, JSON.stringify(rd));
        vm_on_connect(server, JSON.stringify(rd));
        return new Response(null, { status: 101, webSocket: client });
    }
    async webSocketMessage(ws, message) {
        vm_on_message(ws, 0, message);
    }
    async webSocketClose(ws, code, reason, wasClean) {
        vm_on_close(ws);
    }
}

export default {
    async fetch(request, env, ctx) {
        if (request.headers.get('Upgrade') !== 'websocket') {
            return new Response('Expected WebSocket upgrade', { status: 426 });
        }
        const doId = env.WEBSOCKET_DO.idFromName('default');
        const stub = env.WEBSOCKET_DO.get(doId);
        return stub.fetch(request);
    }
};
