/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const vm_get_state: (a: number) => void;
export const vm_init: (a: number, b: number, c: number, d: number, e: number) => void;
export const vm_on_close: (a: number, b: number, c: number) => void;
export const vm_on_connect: (a: number, b: number, c: number, d: number, e: number) => void;
export const vm_on_http_request: (a: number, b: number, c: number) => void;
export const vm_on_message: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const vm_register_connection: (a: number, b: number, c: number, d: number, e: number) => void;
export const vm_set_state: (a: number, b: number, c: number) => void;
export const _matchbox_get_instance_keys: (a: number, b: number) => number;
export const _matchbox_get_instance_prop: (a: number, b: number, c: number, d: number) => number;
export const _matchbox_invoke_callback: (a: number, b: number, c: number, d: number, e: number) => void;
export const _matchbox_pump_vm: (a: number, b: number) => void;
export const _matchbox_set_instance_prop: (a: number, b: number, c: number, d: number, e: number) => void;
export const __wasm_bindgen_func_elem_422: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_1542: (a: number, b: number) => void;
export const __wasm_bindgen_func_elem_838: (a: number, b: number, c: number, d: number, e: number) => number;
export const __wasm_bindgen_func_elem_835: (a: number, b: number, c: number, d: number) => number;
export const __wasm_bindgen_func_elem_836: (a: number, b: number, c: number, d: number) => number;
export const __wasm_bindgen_func_elem_1968: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_1982: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_834: (a: number, b: number, c: number) => number;
export const __wasm_bindgen_func_elem_837: (a: number, b: number, c: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
